const express=require('express');
const app=express();
app.use(require('../controllers/usuario'));
app.use(require('../controllers/departamento'));
app.use(require('../controllers/login'));
app.use(require('../controllers/provincia'));
app.use(require('../controllers/distrito'));
app.use(require('../controllers/persona'));
app.use(require('../controllers/carrera'));
app.use(require('../controllers/periodo'));
app.use(require('../controllers/tipoasignatura'));
app.use(require('../controllers/asignatura'));
app.use(require('../controllers/planEstudio'));
app.use(require('../controllers/sede'));
app.use(require('../controllers/upload'));
app.use(require('../controllers/imagenes'));
app.use(require('../controllers/estado'));
app.use(require('../controllers/ambiente'));
app.use(require('../controllers/horario'));
app.use(require('../controllers/escala'));
app.use(require('../controllers/concepto'));
app.use(require('../controllers/escalaCarrera'));
app.use(require('../controllers/sexo'));
app.use(require('../controllers/estudiante'));
app.use(require('../controllers/tipoEstudiante'));
app.use(require('../controllers/ctaCorriente'));
app.use(require('../controllers/carreraAsignatura'));
app.use(require('../controllers/tipoCarrera'));
app.use(require('../controllers/fechaVencPen'));

module.exports=app;